# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  net_ip = "10.253.0"

  config.vm.box = "ubuntu/xenial64"
  config.hostmanager.enabled=true

  config.vm.define :nimbus do |nimbus|
    nimbus.vm.hostname = :nimbus
    nimbus.vm.network "private_network", ip: "#{net_ip}.10", hostsupdater: "skip"

    nimbus.vm.provider "virtualbox" do |vb|
      vb.name = "nimbus"
      vb.memory = "1024"
      vb.cpus = "1"

    #   Add Provisioning here
    end
  end


  config.vm.define :zookeeper do |zookeeper|
    zookeeper.vm.network "private_network", ip: "#{net_ip}.11", hostsupdater: "skip"
    zookeeper.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y zookeeper zookeeperd
    SHELL
  end

  [
      ["supervisor1", "#{net_ip}.12", "1024"],
      ["supervisor2", "#{net_ip}.13", "1024"],

  ].each do |vmname, ip, mem|
    config.vm.define "#{vmname}" do |supervisor|
      supervisor.vm.hostname = "#{vmname}"
      supervisor.vm.network "private_network", ip: "#{ip}", hostsupdater: "skip"
      supervisor.vm.provider "virtualbox" do |vb|
        vb.name = "storm-#{vmname}"
        vb.memory = "#{mem}"
        vb.cpus = "1"
      end

      #supervisor.vm.provision
    end
  end

end
